### ISSUE TITLE
Fix schedule on index.md docs page

### ISSUE THREAD

**Issue by tleyler** [UWB-ACM/Hackathon-Docs-2020#15]
Jekyll doesn't seem to support/render markdown table syntax natively 💔 

![image](https://user-images.githubusercontent.com/44280730/74608793-ff7f3800-5098-11ea-9e27-c3000146d174.png)

**Comment by tleyler** [comment]
I will merge a fix for this by the end of the weekend 👍

**Comment by etcadinfinitum** [comment]
@tcumings if you add a blank line between the HTML comment and the table header it gets rendered correctly. Markdown is silly sometimes
